### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by maxhillaert** [bamboo/purescript-electron#15]
Hi,

They are quite a few open pull request to upgrade this repo at least to the latest libraries.  Are you planning to merge these or are you removing yourself from this?

Cheers

Max

**Comment by alexandradeas** [comment]
I've assumed this repo is dead for a while now, @narinari has a fork of this repo (https://github.com/narinari/purescript-electron) and seems to have made the changes you wanted in your PR. You might have a better response by using that one instead?

**Comment by bamboo** [comment]
Hi @maxhillaert, it is.

**Comment by bamboo** [comment]
I've updated the README.md to avoid confusion in the future.
