### ISSUE TITLE
IPC bindings, ideas?

### ISSUE THREAD

**Issue by ghost** [bamboo/purescript-electron#9]
Hi!

I'm currently working on PureScript bindings for the [ipcMain](http://electron.atom.io/docs/api/ipc-main/) and [ipcRenderer](http://electron.atom.io/docs/api/ipc-renderer/) part of the Electron API.

As a PureScript amateur, I've a few questions though about how to implement it, so that it has a better chance of being merged and we end up with a higher quality binding.
1. How should we handle the listener parameter? This is a callback function that must be passed to the `on` function. But it's also used to remove the listener using for example the `removeListener`. I've seen that in [purescript-dom](https://github.com/purescript-contrib/purescript-dom/blob/master/src/DOM/Event/EventTarget.purs) a foreign type `EventListener` is used. Should we adopt the same approach?
2. How should we handle the optional multiple arguments to the `send` and callback functions? Use an `Array Json` or something (and convert the array to multiple arguments in JavaScript using [`apply`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply))? 
3. The `ipcRenderer` is only available from the BrowserWindow, and the `ipcMain` is only available from the main process. Should we use types to enforce this? If so, how?

Thanks in advance for any feedback and hints!

**Comment by archblob** [comment]
Hi @mjepronk , I've made a pull request with what I'm currently using.

Regarding your points:
1. Yes.
2. I don't think we should have varargs of any form. The approach I used is to always have one     argument and pass Unit when we don't need it.
3. I'd love to use types to enforce this but I don't think this is the right layer of abstraction at which we should approach this. This should be bare bones bindings and you should be able to build another library on top that enforces the separation and exposes nicer types.

**Comment by ghost** [comment]
Wow, thanks! I'm going to use your bindings in my Electron app.

**Comment by ghost** [comment]
This is fixed with commit 2de7e2d.
